# Generated by Django 3.1.4 on 2020-12-03 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file1',
            new_name='file',
        ),
    ]
