# Generated by Django 3.1.4 on 2020-12-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_auto_20201203_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file',
            new_name='file1',
        ),
        migrations.RemoveField(
            model_name='file',
            name='remark',
        ),
        migrations.AddField(
            model_name='file',
            name='width',
            field=models.FloatField(default=0),
        ),
    ]
